# Generated by Django 4.0.6 on 2022-08-04 08:40

# DJANGO
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1028)),
                ("answer", models.CharField(max_length=1028)),
                ("box", models.IntegerField(default=1)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
