# Generated by Django 4.0.6 on 2022-08-04 12:52

# DJANGO
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="box",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
